"""create endgame_position table

Revision ID: 66bed5f98db4
Revises: 
Create Date: 2026-04-26 09:10:14.289979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66bed5f98db4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endgame_position',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('combination', sa.String(length=20), nullable=False),
    sa.Column('fen', sa.String(length=100, collation='utf8mb4_bin'), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fen')
    )
    op.create_index(op.f('ix_endgame_position_combination'), 'endgame_position', ['combination'], unique=False)
    op.create_index(op.f('ix_endgame_position_difficulty'), 'endgame_position', ['difficulty'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endgame_position_difficulty'), table_name='endgame_position')
    op.drop_index(op.f('ix_endgame_position_combination'), table_name='endgame_position')
    op.drop_table('endgame_position')
    # ### end Alembic commands ###
